### ISSUE TITLE
EDGECLOUD-5456: Unity SDK: Should check for null SignalStrength object if no SIM.

### ISSUE THREAD

**Issue by lgarner** [mobiledgex/edge-cloud-sdk-unity#167]
https://github.com/mobiledgex/edge-cloud-sdk-unity/blob/ad69be29800bcf9544a8b1dfff7ab8687a397ea5/Runtime/Scripts/CarrierInfoIntegration.cs#L181

**Comment by ah1053** [comment]
@lgarner  I guess this issue can be closed now.

**Comment by ah1053** [comment]
Fixed in https://github.com/mobiledgex/edge-cloud-sdk-unity/pull/168
